EDWars/Controllers/LobbiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using EDWars.Hubs;
using EDWars.Models;
using WebMatrix.WebData;

namespace EDWars.Controllers
{
    public class LobbiesController : Controller
    {
        protected readonly UsersContext db = new UsersContext();
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Create()
        {
            var campaign = new Campaign();
            return View(campaign);
        }

        public ActionResult AvailableMapsPartial()
        {
            var maps = db.Maps.ToList();
            return PartialView(maps);
        }

        public ActionResult AvailableCommanders()
        {
            var commanders = db.Commanders.ToList();
            return PartialView(commanders);
        }

        public ActionResult FactionsPartial()
        {
            var factions = db.Factions.ToList();
            return PartialView(factions);
        }
    

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(Campaign campaign)
        {
            if (ModelState.IsValid)
            {
                var map = db.Maps.FirstOrDefault(c => c.id == campaign.mapId.Value);
                if (map == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var Factions = db.Factions.ToList();
                campaign.map = map;
                campaign.blueTeam = new Team();
                campaign.blueTeam.faction = Factions.FirstOrDefault(c => c.name == "Alliance");
                campaign.blueTeam.name = "Blue Team";
                campaign.redTeam = new Team();
                campaign.redTeam.faction = Factions.FirstOrDefault(c => c.name == "Federation");
                campaign.redTeam.name = "Red Team";
                campaign.spectatingTeam = new Team();
                campaign.spectatingTeam.name = "Spectators";

                db.Campaigns.Add(campaign);
                db.SaveChanges();
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LobbyChat.Static_Update_Campaigns(campaign);
            return RedirectToAction("MatchMaking", new{Id =campaign.id});
        }

        [Authorize]
        public ActionResult MatchMaking(int? Id)
        {
            if (Id == null)
            {
                return HttpNotFound();
            }

            var campaign = db.Campaigns.FirstOrDefault(c => c.id == Id);

            if (campaign == null)
            {
                return HttpNotFound();
            }

            return View(campaign);

        }

        public ActionResult CreateCampaignPartial()
        {
            return PartialView();
        }
    }
}

EDWars/Views/Lobbies/AvailableCommanders.cshtml
@model IEnumerable<EDWars.Models.Commander>
<ul class="bxslider commanderlist" style="margin: 0px; list-style: none; padding: 0;">
    @foreach (var commander in Model)
    {
        <li>
            <a class="commander-select" data-commanderId="@commander.Id">
                <div class="map-maker" style="background-color: #eee;">
                    <img src="@commander.imgUrl" alt="@commander.name"/>
                    <h2 style="text-align: center;">@commander.name</h2>
                    <p style="text-align: center;">@commander.description</p>
                </div>

                <div class="commander-abilities">
                    <ul class="abilities">
                        @foreach (var ability in commander.abilities)
                        {
                            <li class="ability">
                                <div style="float: left; width: 64px;"><img class="ability-icon" src="@ability.taskBarBadgeUrl" /></div>
                                <div style="float: left; margin: 4px; width: calc(100% - 72px);">
                                    <h3>@ability.name <sup>lvl @ability.levelAvailable</sup></h3>
                                    <p>@ability.description</p>
                                   
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </a>
        </li>
    }
</ul>

EDWars/Views/Lobbies/AvailableMapsPartial.cshtml
@model IEnumerable<EDWars.Models.Map>
<ul class="bxslider mapslist" style="margin: 0px; list-style: none; padding: 0;">
    @foreach (var map in Model)
    {
        <li>
            <a class="map-select" href="#@map.id" data-mapname="@map.name" data-mapid="@map.id">
                <div class="map-maker" style="background-color: #eee;">
                    <img src="@map.imageUrl" alt="@map.name" />
                    <h2 style="text-align: center;">@map.name</h2>
                    <p style="text-align: center;">@map.description</p>
                </div>
            </a>
        </li>
    }
</ul>

EDWars/Views/Lobbies/Create.cshtml
@using EDWars.Models
@using Newtonsoft.Json.Linq
@model EDWars.Models.Campaign
         
<section id="contact" class="pfblock screen-height">
    <div class="container white">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="pfblock-header">
                    <h2 class="pfblock-title" style="color: white;">Create Campaign</h2>
                    <div class="pfblock-line"></div>
                    <div class="pfblock-subtitle">
                       Select a map
                    </div>
                </div>
            </div>
        </div><!-- .row -->
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
             @{ Html.RenderAction("AvailableMapsPartial"); }
            </div>
        </div>
       

        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                
                @using (Html.BeginForm("Create", "Lobbies", FormMethod.Post, new { id = "create-campaign-form" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)

            
                    @Html.HiddenFor(model => model.mapId, new {htmlAttributes = new {@placeholder = "map name", @class = "form-control"}})
                 
                    <div class="form-group wow fadeInUp">
                        <label class="sr-only" for="map">map name</label>
                        <input class="form-control" placeholder="map name" id="map-name"/>
                    </div>
                    <div class="ajax-hidden">
                        <div class="form-group wow fadeInUp" data-wow-delay=".2s">
                            @Html.TextAreaFor(m => m.notes, new {@placeholder = "Campaign notes", @class = "form-control"})
                        </div>
                        <input type="submit" class="btn btn-success btn-block wow fadeInUp" value="create" data-wow-delay=".3s"/>
                    </div>
                }
            </div>
        </div><!-- .row -->
    </div><!-- .container -->
</section>
<!-- Scroll to top -->
<div class="scroll-up">
    <a id="totop" href="/" style="width: 75px;">Lobbies</a>
</div>
@section scripts
{

    <script>
        $(".screen-height").height($(window).height());

        $(".map-select").click(function(e) {
            $('#mapId').val(this.hash.substr(1));
            $('#map-name').val(this.dataset.mapname);
            alertify.success(this.dataset.mapname + ' map selected');
        });

        $(window).resize(function() {
            $(".screen-height").height($(window).height());
        });
        $(document).ready(function() {
            $('.bxslider').bxSlider();
        });
    </script>

}

EDWars/Views/Lobbies/CreateCampaignPartial.cshtml
<div class="col-lg-12">
    <a href="lobbies/create" class="btn btn-primary btn-block wow fadeInUp" data-wow-delay=".3s">Create campaign</a>
</div>

EDWars/Views/Lobbies/FactionsPartial.cshtml
@using EDWars.Models
@model IEnumerable<EDWars.Models.Faction>
<ul class="factionslider" style="min-height: 300px;">
    @foreach (var faction in Model)
    {
        <li>
            <div class="faction-select" href="#@faction.id" data-faction="@faction.name">
                <div class="map-maker" style="background-color: #eee;">
                    <img src="@faction.imgUrl" alt="@faction.name" style="width: 150px; margin: auto;"/>
                    <h2 style="text-align: center;">@faction.name</h2>
                    @if (faction.winPercentage > 0)
                    {
                        <p style="text-align: center;">Win Rate: @faction.winPercentage%</p>
                    }
                    <div class="faction-abilities">
                        <h3 style="text-align: center;">Abilities</h3>
                        <div style="width: 100%;">
                            @foreach (var ability in faction.factionAbilities)
                            {

                                <div style="width: 125px; margin: auto;">
                                    <img src="@ability.taskBarBadgeUrl"/>
                                </div>
                                <div>
                                    <h3>@ability.name</h3>
                                    <p>@ability.description</p>
                                </div>

                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="faction-picker" type="button" data-faction="@faction.id" class="btn btn-primary">select</button>
            </div>
        </li>
    }
</ul>

EDWars/Views/Lobbies/Index.cshtml
<section class="pfblock pfblock-gray  screen-height" style="background: url(../images/stars.jpg); background-repeat: no-repeat;">
    <div class="home-overlay"></div>
    <div class="container white">
        <div class="row">
            <div class="col-sm-12">
                <div class="pfblock-header wow fadeInDown">
                    <h1 class="pfblock-title white">Campaigns</h1>
                    <div class="pfblock-subtitle">
                        Create or join a lobby to get into the fight.
                    </div>
                    <div class="pfblock-line"></div>
                </div>
            </div>
        </div>
        <div class="row" id="campaign-area">
           
                @if (User.Identity.IsAuthenticated)
                {
                      Html.RenderAction("CreateCampaignPartial");
                        }
                        else
                        {

                        Html.RenderAction("Register", "Account", new { area = "" });
                        }

                    </div>
        <div id="campaign-list" class="row" data-bind="foreach:campaigns.campaigns" style="max-height: 734px;overflow-y: auto; margin-bottom: 8px; margin-top: 8px;">
            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="grid wow zoomIn">
                    <a data-bind="attr: { href: url}">
                        <figure class="effect-bubba">
                            <img src="~/Images/logo-elite-dangerous.png" data-bind="attr: { src: mapImage, alt: mapName}" />
                            <figcaption>
                                <h2 data-bind="text: mapName">Loading <span data-bind="text: users"></span></h2>
                                <img data-bind="attr: { src: redFaction}" style="float: left; max-width: 50px;"/>
                                <img data-bind="attr: { src: blueFaction}" style="float: right; max-width: 50px;" />
                                <p style="text-decoration: underline;" data-bind="text: status"></p>
                                <p data-bind="text: notes"><i class="fa fa-circle-o-notch fa-spin"></i></p>
                            </figcaption>
                        </figure>
                    </a>
                </div>
            </div>
        </div>
        <div class="row" id="chat-area">

            <div class="col-sm-12">
                <div class="pfblock-header wow fadeInUp">
                    <h3 class="pfblock-title white">Comms Chatter</h3>
                    <div class="pfblock-subtitle" style="background-color: white; color: black; text-align: left; padding: 5px; margin-bottom: 4px;">
                        <div id="chat-messages" data-bind="foreach:chat.messages" style=" max-height: 250px; min-height: 80px; overflow-y: auto;">
                            <div data-bind="text:$data"></div>
                        </div>
                    </div>
                    <div class="form-group wow fadeInUp">
                        <label class="sr-only" for="lobby_message">Message</label>
                        <input type="text" class="form-control" id="lobby_message" name="lobby_message" placeholder="Message" data-bind="value:chat.message">
                    </div>
                    <button id="chat-button" type="submit" class="btn btn-primary btn-block btn-primary wow fadeInUp" data-wow-delay=".3s" data-bind="click:sendMessage">
                        Send Message
                    </button>
                </div>
            </div>
        </div>
    </div><!-- .container -->
</section>
<!-- Scroll to top -->
<div class="scroll-up">
    <a id="totop" href="/" style="width: 75px;" >Home</a>
</div>

@section scripts
{
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/underscore.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.0.js"></script>
    <script src="~/SignalR/hubs"></script>
    <script src="~/Scripts/knockout-3.4.0.debug.js"></script>
    <script src="~/Scripts/LobbyChat.js"></script>

    <script>
        $(".screen-height").height($(window).height());
        $('#lobby_message').keyup(function(e) {
            if (e.keyCode === 13) {
                $("#chat-button").click();
            }
        })
        $(window).resize(function () {
            $(".screen-height").height($(window).height());
        });
    </script>
}

EDWars/Views/Lobbies/MatchMaking.cshtml
@model EDWars.Models.Campaign

<section class="pfblock pfblock-gray" style="background: url(/../images/matchmakingbg.jpg) no-repeat center center fixed; background-size: 100% auto; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;">
    <div style="position: absolute">
        <div class="spectators" style="position: relative; padding-top: 24px;">
            <h3 class="pfblock-header wow fadeInDown animated" style="color: white;"> spectators</h3>
            
            <button class="btn btn-lg btn-block" id="joinSpectators" >Join</button>
          
            <div id="spectator-list" data-bind="foreach:campaign.spectatingTeam.players()">
                <div class="player">
                    <div style="float: left; text-align: right;">
                        <h4 data-bind="text:username"></h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container" style="background-image: url('/images/pattern.png'); background-color: rgba(221, 238, 255, 0.52); background-repeat: repeat;">
        <div class="row" style="padding-top: 24px;">
            <div class="col-lg-12">
                <h3 style="color: white;"> you are on <span data-bind="text:teamName()"></span>
                </h3>
                <span style="color: white; font-size: 1.25em; float: right;">Auto Start: <span id="countDown">__</span></span>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-lg-offset-3">
                <div class="pfblock-header wow fadeInDown animated" style="visibility: visible; animation-name: fadeInDown;">
                    <img style="max-width: 125px;" src="~/Images/logo-elite-dangerous.png"/>
                    <div class="pfblock-line"></div>
                </div>
            </div>
        </div>
       
        <div class="row">
            <div class="col-lg-3">
                <div class="white-panel">
                    <h3 style="color: white; text-align: center;" data-bind="text:campaign.redTeam.name">Red Team</h3>
                    <!-- ko if: teamName() !== campaign.redTeam.name() -->
                    <button class="btn btn-lg btn-block" data-bind="enable: campaign.redTeam.players().length < 5, event:{click: joinRed}" id="joinRed">Join</button>
                    <!-- /ko -->
                    <img src="~/Images/logo-elite-dangerous.png" data-bind="attr: { src: campaign.redTeam.faction.imgUrl()}" style="max-width: 50px; float: left;"/>
                    <h4 style="color: white;"><span data-bind="text: campaign.redTeam.faction.name()"></span> 
                        <!-- ko if: teamName() === campaign.redTeam.name() -->
                        <!-- ko if: teamLeader() -->
                        <button data-bind="event:{click:pickRedfaction}" class="btn btn-lg">Change</button>
                        <!-- /ko -->
                        <!-- /ko -->
                    </h4>
                    <hr/>
                    <div id="player-list" data-bind="foreach:campaign.redTeam.players()">
                        <div class="player">
                            <div class="player-profile" data-bind="if: commander()">
                                <img src="~/Images/profile.png" data-bind="attr: { src: commander().imgUrl}"/>
                            </div>
                            <div style="float: right; width: 50%; text-align: right;">
                                <h4 data-bind="text:username"></h4>
                                <h4 data-bind="text: commander().name">commander chosen</h4>
                                <!-- ko if: !me -->
                                <div data-bind="if:Ready()">
                                    <p class="label label-success">Ready</p>
                                </div>
                                <div data-bind="if:!Ready()">
                                    <p class="label label-primary">Picking</p>
                                </div>
                                <!-- /ko -->
                                <!-- ko if: me -->
                                <div data-bind="if:!Ready()">
                                    <button class="btn btn-xs btn-success" data-bind="event:{click: playerReady}" style="float: right;">Ready</button>
                                </div>
                                <div data-bind="if:Ready()">
                                    <button class="btn btn-xs btn-danger" data-bind="event:{click: playerNotReady}" style="float: right;">Not Ready</button>
                                </div>
                                <!-- /ko -->
                            </div>
                            <div style="width: 100%; margin-top: 4px; float: left;">
                                <!-- ko if: me -->
                                    <div data-bind="if:!Ready()">
                                        <button class="btn btn-xs btn-primary btn-block" data-bind="event:{click: commanderSelectBox}" style="float: left;">Select commander</button>
                                    </div>
                                <!-- /ko -->
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="white-panel" style="margin-bottom: 12px;">
                    <h4 style="color: white;"><span data-bind="text: campaign.map().name"></span> 
                      
                    </h4>
                    <hr/>
                    <!-- ko if: matchMaster()  -->
                    <button class="btn btn-lg btn-block" data-bind="event:{click:pickMap}">Change map</button>
                    <!-- /ko -->
                    <div class="grid wow zoomIn">
                        <figure class="effect-bubba">
                            <img src="" data-bind="attr: { src: campaign.map().imageUrl}"/>
                            <figcaption>
                                <h2 data-bind="text: campaign.map().name"></h2>
                                <p data-bind="text: campaign.map().description"></p>
                            </figcaption>
                        </figure>
                    </div>
                    <!-- ko if: matchMaster() -->
                    <button class="btn btn-success btn-block" data-bind="event:{click:requestStartGameCountDown}">Start</button>
                    <!-- /ko -->
                </div>
            </div>
            <div class="col-lg-3">
                <div class="white-panel">
                    <h3 style="color: white; text-align: center;" data-bind="text:campaign.blueTeam.name">Blue Team</h3>
                    <!-- ko if: teamName() !== campaign.blueTeam.name() -->
                    <button class="btn btn-lg btn-block" data-bind="enable: campaign.blueTeam.players().length < 5, event:{click: joinBlue}" id="joinblue">Join</button>
                    <!-- /ko -->
                    <img src="~/Images/logo-elite-dangerous.png" data-bind="attr: { src: campaign.blueTeam.faction.imgUrl}" style="max-width: 50px; float: left;" />
                    <h4 style="color: white;">
                        <span data-bind="text: campaign.blueTeam.faction.name"></span>
                        <!-- ko if: teamName() === campaign.blueTeam.name() -->
                        <!-- ko if: teamLeader() -->
                        <button data-bind="visible:teamLeader(), event:{click:pickBluefaction}" class="btn btn-lg">Change</button>
                        <!-- /ko -->
                        <!-- /ko -->
                    </h4>
                    <hr />
                    <div id="blue-player-list" data-bind="foreach:campaign.blueTeam.players()">
                        <div class="player">
                            <div class="player-profile" data-bind="if: commander()">
                                <img src="~/Images/profile.png" data-bind="attr: { src: commander().imgUrl}" />
                            </div>
                            <div style="float: right; width: 50%; text-align: right;">
                                <h4 data-bind="text:username"></h4>
                                <h4 data-bind="text: commander().name">commander chosen</h4>
                                <!-- ko if: !me -->
                                <div data-bind="if:Ready()">
                                    <p class="label label-success">Ready</p>
                                </div>
                                <div data-bind="if:!Ready()">
                                    <p class="label label-primary">Picking</p>
                                </div>
                                <!-- /ko -->
                                <!-- ko if: me -->
                                <div data-bind="if:!Ready()">
                                    <button class="btn btn-xs btn-success" data-bind="event:{click: playerReady}" style="float: right;">Ready</button>
                                </div>
                                <div data-bind="if:Ready()">
                                    <button class="btn btn-xs btn-danger" data-bind="event:{click: playerNotReady}" style="float: right;">Not Ready</button>
                                </div>
                                <!-- /ko -->
                            </div>
                            <div style="width: 100%; margin-top: 4px; float: left;">
                                <!-- ko if: me -->
                                <div data-bind="if:!Ready()">
                                    <button class="btn btn-xs btn-primary btn-block" data-bind="event:{click: commanderSelectBox}" style="float: left;">Select commander</button>
                                </div>
                                <!-- /ko -->
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-bottom: 24px;">
            <div class="col-lg-12">
                <div class="pfblock-subtitle" style="background-color: white; color: black; text-align: left; padding: 5px; margin-bottom: 4px;">
                    <div id="chat-messages" data-bind="foreach:chat.messages" style="max-height: 250px; min-height: 80px; overflow-y: auto;">
                        <div data-bind="text:$data"></div>
                    </div>
                </div>
                <div class="form-group wow fadeInUp">
                    <label class="sr-only" for="lobby_message">Message</label>
                    <input type="text" class="form-control" id="lobby_message" name="lobby_message" placeholder="Message" data-bind="value:chat.message">
                </div>
                <button id="chat-button" type="submit" class="btn btn-lg btn-block" data-bind="click:sendMessage">
                    Send Message
                </button>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                @*<pre data-bind="text: ko.toJSON($data, null, 2)"></pre>*@
            </div>
        </div>
    </div>
</section>

<!-- Scroll to top -->
<div class="scroll-up">
    <a id="totop" href="/lobbies" style="width: 75px;">Lobbies</a>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="factionslist">
    <div class="modal-dialog" style="min-height: 300px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Choose a faction</h4>
            </div>
            <div class="modal-body" style="min-height: 300px;">
              @{ Html.RenderAction("FactionsPartial"); }
            </div>
          
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade" tabindex="-1" role="dialog" id="mapslist">
    <div class="modal-dialog" style="min-height: 300px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" style="text-align: center;">Choose a map</h4>
            </div>
            <div class="modal-body" style="min-height: 300px;">
                @{ Html.RenderAction("AvailableMapsPartial"); }
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" tabindex="-1" role="dialog" id="commanderList">
    <div class="modal-dialog" style="min-height: 300px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" style="text-align: center;">Choose a commander</h4>
            </div>
            <div class="modal-body" style="min-height: 300px;">
                @{ Html.RenderAction("AvailableCommanders"); }
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
@section scripts
{
<script src="~/Scripts/jquery.signalR-2.2.0.js"></script>
<script src="~/SignalR/hubs"></script>
<script src="~/Scripts/MatchMaking.js"></script>
<script>
    $(document).ready(function () {
        window.slider = $('.factionslider').bxSlider();
        window.mapSlider = $('.mapslist').bxSlider();
        window.commandSlider = $('.commanderlist').bxSlider();
    });
</script>
}